### ISSUE TITLE
Fix overflow error on the Add Tags screen

### ISSUE THREAD

**Issue by mauryakshitij** [letsintegreat/Tagify#13] opened 2022-12-05 09:03 UTC
![WhatsApp Image 2022-12-05 at 14 30 50](https://user-images.githubusercontent.com/95132851/205596529-03efbff1-093d-4f19-9c03-0b3bc85097f7.jpg)

The keyboard popup causes an overflow error on the bottom of the screen

**Comment by ehsanNazari145** [comment] 2022-12-05 10:47
you have to wrap your main widget by SingleChildeScrollViwe.
in your code is a container after **`body:`**

**Comment by chandansgowda** [comment] 2022-12-06 03:38
Hey @letsintegreat ,
Shall I take this up ?

**Comment by letsintegreat** [comment] 2022-12-06 04:33
@chandansgowda Sure, assigning it to you!

**Comment by chandansgowda** [comment] 2022-12-06 08:06
Hey @letsintegreat 
I'm getting this error when I'm trying to signin using my account. Can you please help me with it ?


I/FA      (13180): Tag Manager is not found and thus will not be used
E/FA      (13180): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
E/FA      (13180): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
E/FA      (13180): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
E/flutter (13180): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 12500: , null, null)
E/flutter (13180): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (13180): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter (13180): <asynchronous suspension>
E/flutter (13180): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:499:43)
E/flutter (13180): <asynchronous suspension>
E/flutter (13180): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:273:30)
E/flutter (13180): <asynchronous suspension>
E/flutter (13180): #4      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:407:5)
E/flutter (13180): <asynchronous suspension>
E/flutter (13180):

**Comment by letsintegreat** [comment] 2022-12-06 08:10
@chandansgowda While enabling Google Sign In in Firebase Console, it asks you to add a SHA1 fingerprint in your project settings. I think not adding a SHA1 fingerprint is the cause of this error.

[Here](https://stackoverflow.com/questions/39144629/how-to-add-sha-1-to-android-application) is how you can add it. There are multiple answers in this link, choose the one which works for you.

**Comment by chandansgowda** [comment] 2022-12-06 08:41
@letsintegreat I have added it already. I also replaced the new google-services.json file. Even then the error is the same.

**Comment by chandansgowda** [comment] 2022-12-06 08:48
Hey @letsintegreat 
I digged deep and found that I had forgot to enable google signin itself on firebase. I'm working on the issue now.
Thanks

**Comment by letsintegreat** [comment] 2022-12-06 08:49
@chandansgowda Did you use FlutterFire CLI to configure the app? Also can you ping me on discord, so that we can continue the discussion there.

**Closed** 2022-12-06 09:05 UTC
Labels: bug, Codepeak22, good-first-issue
